---
- name: install and start httpd
  hosts: web
  gather_facts: no
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
        update_cache: true
    - name: start httpd service
      service:
       enabled: true
       name: httpd
       state: started
