---
- name: install list of software
  hosts: all
  become: yes
  gather_facts: no
  vars:
    packages:
      - htop
      - telnet
      - net-tools
      - neofetch
  tasks:
    - name: install list
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      with_items: '{{ packages }}'
