---
- name: install list of software
  hosts: web
  tasks:
    - name: install list
      yum:
        name: {{ item }}
        state: present
      with_items:
        - httpd
        - htop
        - telnet
        - net-tools
