---
- name: install list of software
  hosts: all
  gather_facts: no
  tasks:
    - name: install list
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - pydf
        - htop
        - telnet
        - net-tools
